create table issue
(
    id               bigint generated by default as identity
        constraint issue_pkey
            primary key,
    description      varchar(100),
    details          varchar(300),
    date             timestamp,
    issue_status     varchar(50),
    assignee_user_id bigint
        constraint fk_issue_user
            references users,
    created_at       timestamp,
    created_by       varchar(100),
    updated_at       timestamp,
    updated_by       varchar(100)
);

alter table issue
    owner to postgres;


----issuehistory table
create table issue_history
(
    id               bigint generated by default as identity
        constraint issue_history_pkey
            primary key,
    issue_id         bigint
        constraint fk_issueid
            references issue,
    description      varchar(300),
    date             timestamp,
    issue_status     varchar(50),
    details          varchar(50),
    assignee_user_id bigint
        constraint fk_userid
            references users,
    created_at       timestamp,
    created_by       varchar(100),
    updated_at       timestamp,
    updated_by       varchar(100)
);

create table issue_status
(
    issue_status varchar(50),
    constraint fk_issue foreign key (issue_status) references issue(issue_status),
    constraint fk_issue_hst foreign key (issue_status) references issue_history(issue_status)
);

alter table issue_history
    owner to postgres;


-----------------
--project table
create table project
(
    id              bigint generated by default as identity
        constraint project_pkey
            primary key,
    project_code    varchar(30),
    project_name    varchar(300),
    manager_user_id bigint
        constraint fk_manager_user
            references users,
    created_at      timestamp,
    created_by      varchar(100),
    updated_at      timestamp,
    updated_by      varchar(100)
);

alter table project
    owner to postgres;



---users table

create table users
(
    id               bigint generated by default as identity
        constraint users_pkey
            primary key,
    uname            varchar(30)
        constraint users_uname_key
            unique,
    pwd              varchar(30),
    date             timestamp,
    "name_Surname"   varchar(100),
    email            varchar(50),
    assignee_user_id bigint,
    created_at       timestamp,
    created_by       varchar(100),
    updated_at       timestamp,
    updated_by       varchar(100)
);

alter table users
    owner to postgres;

--commit;


